config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end
    
  root to: 'menus#index'
  resources :menus
  resources :users
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sokuseki
  belongs_to :sokuseki_mon
  belongs_to :sokuseki_tue
  belongs_to :sokuseki_wed
  belongs_to :sokuseki_thu
  belongs_to :sokuseki_fri
  belongs_to :sokuseki_sat
  belongs_to :user

  with_options numericality: { other_than: 1 } do
    validates :sokuseki_id
    validates :sokuseki_mon_id
    validates :sokuseki_tue_id
    validates :sokuseki_wed_id
    validates :sokuseki_thu_id
    validates :sokuseki_fri_id
    validates :sokuseki_sat_id
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def self.guest
    find_or_create_by(email: 'test@com') do |user|
      user.password = Rails.application.secrets.test_account_pass
    end
  end

  def index
    @menus = Menu.includes(:user).order('created_at DESC')
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    menu = Menu.find(params[:id])
    menu.update(menu_params)
    redirect_to action: :index
  end

  private

  def menu_params
    params.require(:menu).permit(:sun_making, :mon_making, :tue_making, :wed_making, :thu_making, :fri_making, :sat_making, :sokuseki_id, :sokuseki_mon_id, :sokuseki_tue_id, :sokuseki_wed_id, :sokuseki_thu_id, :sokuseki_fri_id, :sokuseki_sat_id).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/index.html.erb
<div class="contents">
<div class="taito"><h1>今週のメニューはこちら</h1></div>
<div class="kondate">
  <% @menus.each do |menu| %>
    <div class=user_name>
     <a href="/users/<%= menu.user.id %>"><%="#{menu.user.name}さん"%></a>
    </div> 
    <div class="week">
        <div class="week-menu">
          <p>日曜日</p>
          <hr>
          <div class="week-resipi"><%= menu.sokuseki.name %></div>
        </div> 
        <div class="week-menu">
          <p>月曜日</p>
          <hr>
          <div class="week-resipi"><%= menu.sokuseki_mon.name %></div>
        </div>

        <div class="week-menu">
          <p>火曜日</p>
          <hr>
          <div class="week-resipi"><%= menu.sokuseki_tue.name %></div>
        </div>

        <div class="week-menu">
           <p>水曜日</p>
           <hr>
           <div class="week-resipi"><%= menu.sokuseki_wed.name %></div>
        </div>

        <div class="week-menu">
          <p>木曜日</p>
          <hr>
          <div class="week-resipi"><%= menu.sokuseki_thu.name %></div>
        </div>
        <div class="week-menu">
          <p>金曜日</p>
          <hr>
          <div class="week-resipi"><%= menu.sokuseki_fri.name %></div>
        </div>

        <div class="week-menu">
           <p>土曜日</p>
           <hr>
           <div class="week-resipi"><%= menu.sokuseki_sat.name %></div>
        </div>
    </div>
  <% end %>
  </div>
</div>

app/views/menus/new.html.erb
<div class="sinki">
<h3>投稿ページ</h3>
 <p>下のメニューを選んでください</p>
    <%= form_with(model: @menu, local: true) do |f| %>
    
      <%= render 'shared/error_messages', model: f.object %>
       <%#日曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :sun_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>
    

      <%#月曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_mon_id, SokusekiMon.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :mon_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>

      <%#火曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_tue_id, SokusekiTue.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :tue_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>

      <%#水曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_wed_id, SokusekiWed.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :wed_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>
     
      <%#木曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_thu_id, SokusekiThu.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :thu_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>

      <%#金曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_fri_id, SokusekiFri.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :fri_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>
      
      <%#土曜日%>
       <div class="selects">
      <%= f.collection_select(:sokuseki_sat_id, SokusekiSat.all, :id, :name, {}, {class:"genre-select"}) %>
      <div class="selects-text">
      <%= f.text_area :sat_making, placeholder: "手料理ならレシピ記入蘭", rows: "2" %></div>
      </div>

      <%= f.submit "SEND" ,class: :sends %>
    <% end %>
  </div>   

app/views/menus/show.html.erb
   <div class="more_list">
          <%= link_to '編集', edit_menu_path(@menu.id),method: :get %>
      
          <%= link_to '削除', user_path(@menu.id),method: :delete %>
      </div>
    <span class="name"><%= @name %>さん</span>
    <div class="kondate">
  <% @menus.each do |menu| %>
    
     <p><%= link_to "#{menu.user.name}さん", "/users/#{current_user.id}", method: :get %></p>
    
    <div class="week">
        <div class="week-menu">
          <p>日曜日</p>
          <hr>
          <%= menu.sokuseki.name %>
          <p><%= menu.sun_making %></p>
        </div> 
        <div class="week-menu">
          <p>月曜日</p>
          <hr>
          <%= menu.sokuseki_mon.name %>
          <p><%= menu.mon_making %></p>
        </div>

        <div class="week-menu">
          <p>火曜日</p>
          <hr>
          <%= menu.sokuseki_tue.name %>
          <p><%= menu.tue_making %></p>
        </div>

        <div class="week-menu">
           <p>水曜日</p>
           <hr>
          <%= menu.sokuseki_wed.name %>
           <p><%= menu.wed_making %></p>
        </div>

        <div class="week-menu">
          <p>木曜日</p>
          <hr>
          <%= menu.sokuseki_thu.name %>
          <p><%= menu.thu_making %></p>
        </div>
        <div class="week-menu">
          <p>金曜日</p>
          <hr>
          <%= menu.sokuseki_fri.name %>
          <p><%= menu.fri_making %></p>
        </div>

        <div class="week-menu">
           <p>土曜日</p>
           <hr>
           <%= menu.sokuseki_sat.name %>
           <p><%= menu.sat_making %></p>
        </div>
    </div>
  <% end %>
  </div>