config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end
    
  root to: 'menus#index'
  resources :menus
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :menus

  validates :name, presence: true, length: { maximum: 6 }

  def self.guest
    find_or_create_by!(name: 'test',email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @menus = user.menus
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to root_path
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    if current_user.update(menu_params)
      redirect_to root_path
    else
      render :edit
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <h3>編集する</h3>
      <%= form_with(model: @menu, local: true) do |f| %>

       <%#日曜日%>
      <p><%= f.collection_select(:sokuseki_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :sun_making, placeholder: "text", rows: "2" %></p>

      <%#月曜日%>
      <p><%= f.collection_select(:sokuseki_mon_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :mon_making, placeholder: "text", rows: "2" %></p>

      <%#火曜日%>
      <p><%= f.collection_select(:sokuseki_tue_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :tue_making, placeholder: "text", rows: "2" %></p>

      <%#水曜日%>
      <p><%= f.collection_select(:sokuseki_wed_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :wed_making, placeholder: "text", rows: "2" %></p>
     
      <%#木曜日%>
      <p><%= f.collection_select(:sokuseki_thu_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :thu_making, placeholder: "text", rows: "2" %></p>

      <%#金曜日%>
      <p><%= f.collection_select(:sokuseki_fri_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :fri_making, placeholder: "text", rows: "2" %></p>

      <%#土曜日%>
      <p><%= f.collection_select(:sokuseki_sat_id, Sokuseki.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :sat_making, placeholder: "text", rows: "2" %></p>
      <%= f.submit "SEND" %>
    <% end %>
  </div>

app/views/users/show.html.erb
  
    <div class="name"><%= @name %>さん</div>
    <div class="kondate">
  <% @menus.each do |menu| %>
     <% if user_signed_in? && current_user.id == menu.user_id %>
     <%unless @name === 'test'%>
      <div class="more_list">
          <%= link_to '編集', edit_user_path(menu.id),method: :get ,class: :edit_list %>
      
          <%= link_to '削除', user_path(menu.id),method: :delete, class: :edit_list %>
      </div>
      <% end %>
      <% end %>
    
    <div class="week">
        <div class="week-menu">
          <p>日曜日</p>
          <hr>
          <%= menu.sokuseki.name %>
          <hr>
          <div class="cooking"><%= menu.sun_making %></div>
        </div> 
        <div class="week-menu">
          <p>月曜日</p>
          <hr>
          <%= menu.sokuseki_mon.name %>
          <hr>
          <div class="cooking"><%= menu.mon_making %></div>
        </div>

        <div class="week-menu">
          <p>火曜日</p>
          <hr>
          <%= menu.sokuseki_tue.name %>
          <hr>
          <div class="cooking"><%= menu.tue_making %></div>
        </div>

        <div class="week-menu">
           <p>水曜日</p>
           <hr>
           <%= menu.sokuseki_wed.name %>
           <hr>
           <div class="cooking"><%= menu.wed_making %></div>
        </div>

        <div class="week-menu">
          <p>木曜日</p>
          <hr>
          <%= menu.sokuseki_thu.name %>
          <hr>
          <div class="cooking"><%= menu.thu_making %></div>
        </div>
        <div class="week-menu">
          <p>金曜日</p>
          <hr>
          <%= menu.sokuseki_fri.name %>
          <hr>
          <div class="cooking"><%= menu.fri_making %></div>
        </div>

        <div class="week-menu">
           <p>土曜日</p>
           <hr>
           <%= menu.sokuseki_sat.name %>
           <hr>
           <div class="cooking"><%= menu.sat_making %></div>
        </div>
    </div>
  <% end %>
  </div>
    